### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by GX77** [gingsi/coot-videotext#41]
Traceback (most recent call last):
  File "/mnt/Pycharm_Remote/coot/data_read_youcook2_meta.py", line 8, in <module>
    from nntrainer import arguments, utils
  File "/mnt/Pycharm_Remote/coot/nntrainer/arguments.py", line 11, in <module>
    from nntrainer.utils import TrainerPathConst
  File "/mnt/Pycharm_Remote/coot/nntrainer/utils.py", line 17, in <module>
    from nntrainer import typext
  File "/mnt/Pycharm_Remote/coot/nntrainer/typext.py", line 55, in <module>
    class SaveableBaseModel(BaseModel):
  File "/mnt/Pycharm_Remote/coot/nntrainer/typext.py", line 76, in SaveableBaseModel
    def load(self, file: Union[str, Path]) -> SaveableBaseModel:
NameError: name 'SaveableBaseModel' is not defined

**Comment by GX77** [comment]
Can you tell me why ? Thank you~

**Comment by gingsi** [comment]
Hi, probably you have the wrong python version, try it with python 3.8. Best

**Comment by GX77** [comment]
ok thanks
